#!/usr/bin/env sh

[ -e "$HOME/.gemrc" ] || [ -h "$HOME/.gemrc" ] && rm "$HOME/.gemrc"
ln -s "$PWD/.gemrc" "$HOME/.gemrc"

[ -e "$HOME/.hushlogin" ] || [ -h "$HOME/.hushlogin" ] && rm "$HOME/.hushlogin"
ln -s "$PWD/.hushlogin" "$HOME/.hushlogin"

[ -e "$HOME/.zshrc" ] || [ -h "$HOME/.zshrc" ] && rm "$HOME/.zshrc"
ln -s "$PWD/.zshrc" "$HOME/.zshrc"

[ -e "$HOME/.gitconfig" ] || [ -h "$HOME/.gitconfig" ] && rm "$HOME/.gitconfig"
ln -s "$PWD/.gitconfig" "$HOME/.gitconfig"

