#!/usr/bin/env bash

[ -e "$HOME/.gemrc" ] || [ -h "$HOME/.gemrc" ] && rm "$HOME/.gemrc"
ln -s "$PWD/.gemrc" "$HOME/.gemrc"

[ -e "$HOME/.hushlogin" ] || [ -h "$HOME/.hushlogin" ] && rm "$HOME/.hushlogin"
ln -s "$PWD/.hushlogin" "$HOME/.hushlogin"

[ -e "$HOME/.zshrc" ] || [ -h "$HOME/.zshrc" ] && rm "$HOME/.zshrc"
ln -s "$PWD/.zshrc" "$HOME/.zshrc"

[ -e "$HOME/.gitconfig" ] || [ -h "$HOME/.gitconfig" ] && rm "$HOME/.gitconfig"
ln -s "$PWD/.gitconfig" "$HOME/.gitconfig"

[ -e "$HOME/.Xresources" ] || [ -h "$HOME/.Xresources" ] && rm "$HOME/.Xresources"
ln -s "$PWD/.Xresources" "$HOME/.Xresources"

[ -e "$HOME/.Xdefaults" ] || [ -h "$HOME/.Xdefaults" ] && rm "$HOME/.Xdefaults"
ln -s "$PWD/.Xresources" "$HOME/.Xdefaults"

case "$OSTYPE" in
  darwin*)
    SUBLIME_TEXT_DIR="$HOME/Library/Application Support/Sublime Text 3/Packages/User"
  ;;
  linux*)
    SUBLIME_TEXT_DIR="$HOME/.config/sublime-text-3/Packages/User"
  ;;
  *)
    SUBLIME_TEXT_DIR=""
  ;;
esac

if [ ! -z "$SUBLIME_TEXT_DIR" ]
then
  [ -e "$SUBLIME_TEXT_DIR" ] || [ -h "$SUBLIME_TEXT_DIR" ] && rm "$SUBLIME_TEXT_DIR"
  ln -s "$PWD/sublime-text" "$SUBLIME_TEXT_DIR"
fi

